services:
  db:
    image: postgres:16
    container_name: set_db
    environment:
      POSTGRES_USER: set_user
      POSTGRES_PASSWORD: set_pass
      POSTGRES_DB: set_db
    ports:
      - "5432:5432"
    volumes:
      - set_pgdata:/var/lib/postgresql/data

volumes:
  set_pgdata: